[build-system]
requires = [ "setuptools", "wheel" ]
build-backend = "setuptools.build_meta"

[project]
name = "builderbench"
version = "0.1.0"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.11"
authors = [
  {name = "Raj Ghugare"},
  {name = "Catherine Ji"},
  {name = "Kathryn Wantlin"},
  {name = "Jin Schofield"},
  {name = "Benjamin Eysenbach"},
]
maintainers = [
    {name = "Raj Ghugare"}
]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]

dependencies = [
    "mujoco == 3.7.0",
    "mujoco-mjx == 3.7.0",
    "jax[cuda12] == 0.10.0",
    "optax == 0.2.8",
    "etils == 1.14.0",
    "ml-collections == 1.1.0",
]

[project.optional-dependencies]
train = [
    "flax == 0.12.7",
    "distrax == 0.1.8",
    "wandb == 0.26.0",
    "wandb-osh == 1.2.2",
    "tyro == 1.0.13",
]

all = [
    "builderbench[train]",
]

[project.urls]
homepage = "https://rajghugare19.github.io/builderbench"

[tool.setuptools.packages.find]
where = ["."]
include = ["builderbench*"]
